from typing import Dict, List

categories: Dict[str, List[str]] = {
  "Alcohol": [
    r'801 LD RICHMOND LTD',
    r'LIQUOR',
    r'PORTLAND CRAFT',
    r'BREWING',
    r'BREWERY',
    r'BREWHALL',
    r'FUGGLES & WARLOCK',
    r'MOODY ALES',
  ],
  "Transportation/Gas": [
    r'CHEVRON',
    r'SUPER SAVE GAS',
    r'SHELL OIL',
    r'SHELL 3596',
    r'SHELL 5511 GARDEN CITY',
    r'BOUNDARY TOWN PANTRY',
  ],
  "Transportation/Insurance": [
    r'ICBC',
  ],
  "Transportation/Loans": [],
  "Transportation/Maintenance": [
    r'BMS AUTO HAUS',
    r'SPEEDY GLASS',
    r'SENSHA-YA',
    r'NONDA',
  ],
  "Transportation/Parking": [
    r'IMPARK',
    r'EASYPARK',
    r'PAYBYPHONE',
    r'PARKING',
  ],
  "Transportation/Penalties": [
    r'CITY OF VAN-BYLAW FINE',
    r'BUSTERS TOWING',
  ],
  "Bank/Charges": [
    r'BALANCEPROTECTOR PREMIUM',
    r'PURCHASE INTEREST',
    r'OVERLIMIT FEE',
    r'CASH ADVANCE FEE',
    r'ANNUAL FEE',
  ],
  "Bank/Interests": [
    r'CASH ADVANCE INTEREST',
  ],
  "Business/Admin": [
    r'ONESTOP - BCGOV',
    r'BC REGISTRY',
  ],
  "Coffee": [
    r'STARBUCKS',
    r'TIM HORTONS',
    r'THE LOAFE',
    r'BURO VANCOUVER',
    r'COFFEE',
    r'JJ BEAN',
    r'CAFE LA FORET',
    r'LEANNS CAFE',
    r'OUR TOWN',
  ],
  "Commute/Public Transit": [],
  "Digital/Recreation": [
    r'NETFLIX',
    r'PLAYSTATION NETWORK',
    r'SPOTIFY',
  ],
  "Digital/Resources": [
    r'PIXELRESORT',
    r'ENVATOMARKET',
  ],
  "Digital/Utilities": [
    r'PADDLE.NET\* KAPELI\.COM',
    r'CIRCLECI',
    r'EXPRSVPN',
    r'ADOBE',
    r'APPLE SEARCH ADS',
    r'GOOGLE CLOUD SERVICES',
    r'GOOGLE \*SVCSAPPS',
    r'GOOGLE \*CLOUD',
    r'GOOGLE \*GOOGLE STORAGE',
    r'GOOGLE \*TESLACOIL',
    r'GOOGLE \*GSUITE',
    r'GITHUB',
    r'IWANTMYNAME',
    r'PRISMIC\.IO',
    r'SEARCHADS',
  ],
  "Electronics/Accessories": [
    r'LEE S ELECTRONIC',
    r'KONO STORE',
    r'M KEYBOARDS',
    r'SIGNATURE PLASTICS',
    r'GEEKKEYS',
  ],
  "Electronics/Devices": [
    r'APPLE ONLINE STORE',
    r'APPLE STORE',
  ],
  "Electronics/Recreation": [
    r'ITUNES',
  ],
  "Events/Business": [],
  "Events/Recreation": [
    r'COMMODORE BALLROOM',
    r'COMIC CON',
  ],
  "Food": [
    r'LOTUS THE PLACE FOR PHO',
    r'SHANG NOODLE HOUSE',
    r'BEEF NOODLE',
    r'CAPTAIN\'S BOIL',
    r'NYF',
    r'PHO 37',
    r'PHO GOODNESS',
    r'DRIED FRUITE',
    r'GABI & JULES',
    r'CHINA LAN',
    r'BUBBLE WAFFLE',
    r'CAFE GLOUCESTER',
    r'PAJO\'S',
    r'BREAKFAST',
    r'LUNCH',
    r'DOORDASH',
    r'DINER',
    r'DINNER',
    r'BO BO FISH',
    r'MANZO',
    r'POKEY OKEY',
    r'TACOS',
    r'EGGSPECTATION',
    r'HIKARI VANCOUVER',
    r'BREW HOUSE',
    r'POTTERS GARDEN KOREAN',
    r'TALAY THAI',
    r'DISCO CHEETAH KOREAN',
    r'MEET FRESH',
    r'BOILING POINT',
    r'QOOLA',
    r'ZAC ZAC',
    r'TSUKIJI',
    r'JIANGHU',
    r'VEGETARIAN',
    r'SUGAR LAB',
    r'SOODA KOREAN',
    r'BURGOO',
    r'GNARLY ROOT PIZZA',
    r'KITANOYA GUU',
    r'SKIPTHEDISHES',
    r'BANH MI',
    r'EMPIRE SEAFOOD RESTAUR',
    r'BUMP AND GRIND CAFE',
    r'UBER EATS',
    r'HAPPY TREE HOUSE',
    r'GOTHAM STEAKHOUSE',
    r'ME \+ CREPE',
    r'TANGRAM',
    r'FOOD',
    r'TERRA BREADS',
    r'FATBURGER',
    r'SNACK LAND',
    r'ORANGE JULIUS',
    r'RAMEN',
    r'JOHN 3:16',
    r'BISTRO',
    r'CHATIME',
    r'BAKERY',
    r'KENTUCKY FRIED CHICKEN',
    r'KITCHEN',
    r'A&W',
    r'POK POK',
    r'PIZZA',
    r'GYOKIN NAN-NIN',
    r'RESTAURANT',
    r'MAHONY & SONS',
    r'SHIANG GARDEN SEAFOOD',
    r'HEIRLOOM',
    r'GOOD BOWL',
    r'TOP SHANGHAI',
    r'SAL Y LIMON',
    r'MCDONALD',
    r'OYSTER',
    r'RIVERWAY CLUBHOUSE',
    r'COLONY MAIN',
    r'TOO TWO',
    r'BBQ',
    r'ORIGINAL JOE',
    r'SINGLE SHOT',
    r'POP BAR',
    r'COPA CAFE',
    r'CHURCH\'S CHICKEN',
    r'PENANG DELIGHT',
    r'JOEY BURNABY',
    r'THE PIT',
    r'CAFE DE LORANGERIE',
    r'MARUTAMA',
    r'RAIN OR SHINE',
    r'CUISINE',
    r'THE OAKWOOD CANADIAN',
    r'CACTUS CLUB',
    r'NEW SPICY CHILI RESTAURAN',
  ],
  "Groceries": [
    r'WAL-MART',
    r'LONDON DRUGS',
    r'SHOPPERSDRUGMART',
    r'OSAKA #005 RICHMOND BC',
    r'MARKETPLACE IGA',
    r'DARUMAYA',
    r'SUPERSTORE',
    r'TARGET 00003467 CLACKAMAS',
  ],
  "Hobbies": [
    r'BADMINTON',
    r'BOARD GAME',
    r'BOOKS AND VIDEO',
    r'CINEPLEX',
    r'FAMOUS PLAYER',
    r'VANCOUVER STREET BATTLE',
    r'IMPERIAL HOBBIES',
    r'MAGIC STRONGHOLD',
    r'THE BROKEN TOKEN',
    r'BOARDGAMEBLISS',
  ],
  "Household/Bills": [],
  "Household/Enhancements": [
    r'ASSURED ENVIRONMENTAL',
    r'IKEA',
    r'ROOM IN ORDER',
  ],
  "Income": [],
  "Investments/Cryptocurrency": [
    r'COINBASE',
  ],
  "Investments/RRSP": [],
  "Medical/Drugs": [],
  "Medical/Insurance": [],
  "Medical/Practitioners": [],
  "Office Supplies": [
    r'STAPLES STORE',
    r'MICHAELS',
    r'BEST BUY',
    r'CHANGZHOUJI',
  ],
  "Telecom/Home": [
    r'SHAW CABLESYSTEMS',
  ],
  "Telecom/Mobile": [
    r'BELL MOBILITY',
    r'FIDO MOBILE',
    r'T-MOBILE',
  ],
  "Travel": [
    r'DELTA AIR',
    r'EXPEDIA\.CA',
    r'DOLLAR RENT A CAR',
    r'HILTON SF AIRPORT',
    r'STANLEY PARK',
    r'ONLINE BOOKING',
    r'CAR2GO',
    r'USCUSTOMS',
    r'RAILWAY CAF',
    r'BCF - TSAWWASSEN',
    r'BCF-SWARTZ BAY',
    r'CITY OF VICTORIA',
    r'CITY OF PORTLAND',
  ],
  "Shopping": [
    r'AMAZON',
    r'AMZN',
    r'UNIQLO',
    r'MUJI',
    r'REDBUBBLE',
    r'CHAMPS SPORTS',
    r'JJ METROPOLIS',
    r'TSB SHIPPING',
    r'AMAZONPRIME',
    r'IN OUT PARCEL',
    r'THE STOWE',
    r'ALIEXPRESS',
    r'HERSCHEL',
    r'ZARA',
    r'NINETEEN TEN',
    r'ETSY',
    r'APPAREL',
    r'SEPHORA',
  ],
}
